<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="width: 8.98in;overflow: hidden;">
<img style="position:absolute;top:0.00in;left:0.00in;width:3.73in;height:12.76in" src="{{$records->rootFolder}}/vi_1.png" />
<div style="position:absolute;top:11.31in;left:0.47in;width:0.81in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">INTEREST</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div>
<img style="position:absolute;top:11.58in;left:0.47in;width:2.71in;height:0.02in" src="{{$records->rootFolder}}/vi_2.png" />
<div style="position:absolute;top:11.71in;left:0.47in;width:1.81in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Music </span></SPAN><br/></div>
<div style="position:absolute;top:11.71in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.48in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">| </span></SPAN></div><br/></div>
<div style="position:absolute;top:11.71in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.55in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Football </span></SPAN></div><br/></div>
<div style="position:absolute;top:11.71in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:1.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">| </span></SPAN></div><br/></div>
<div style="position:absolute;top:11.71in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:1.26in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Gossip</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:3.16in;left:0.47in;width:2.20in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">PERSONAL </span></SPAN><br/></div>
<div style="position:absolute;top:3.16in;left:0.47in;width:2.20in;line-height:0.30in;"><div style="position:relative; left:0.93in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">INFORMATION</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:8.37in;left:0.47in;width:1.07in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">EDUCATION</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.37in;left:0.47in;width:0.91in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">CONTACT</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.93in;left:0.00in;width:8.98in;height:1.51in" src="{{$records->rootFolder}}/vi_3.png" />
<img style="position:absolute;top:0.80in;left:0.79in;width:1.81in;height:1.81in" src="{{$records->rootFolder}}/ci_1.png" />
<img style="position:absolute;top:3.43in;left:0.47in;width:2.71in;height:0.02in" src="{{$records->rootFolder}}/ci_2.png" />
<img style="position:absolute;top:5.63in;left:0.47in;width:2.71in;height:0.02in" src="{{$records->rootFolder}}/ci_3.png" />
<img style="position:absolute;top:8.65in;left:0.47in;width:2.71in;height:0.02in" src="{{$records->rootFolder}}/ci_4.png" />
<div style="position:absolute;top:1.14in;left:4.21in;width:1.83in;line-height:0.63in;"><span style="font-style:normal;font-weight:normal;font-size:25pt;font-family:Poppins Medium;color:#375063">{{$records->user->lastName}}</span><span style="font-style:normal;font-weight:normal;font-size:25pt;font-family:Poppins Medium;color:#375063"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.52in;left:4.21in;width:2.30in;line-height:0.63in;"><span style="font-style:normal;font-weight:normal;font-size:25pt;font-family:Poppins Medium;color:#375063">{{$records->user->otherNames}}</span><span style="font-style:normal;font-weight:normal;font-size:25pt;font-family:Poppins Medium;color:#375063"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.02in;left:4.21in;width:2.21in;line-height:0.25in;"><div style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">Job Title </span></SPAN></div><br/></div>
<div style="position:absolute;top:2.02in;left:4.21in;width:2.21in;line-height:0.25in;"><div style="position:relative; left:0.66in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">&nbsp; / &nbsp;</span></SPAN></div><br/></div>
<div style="position:absolute;top:2.02in;left:4.21in;width:2.21in;line-height:0.25in;"><div style="position:relative; left:0.75in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">{{$records->user->job_title ?? ''}}</span></SPAN></div><br/></div>
<div style="position:absolute;top:3.64in;left:0.47in;width:0.99in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Date </span></SPAN><br/></div>
<div style="position:absolute;top:3.64in;left:0.47in;width:0.99in;line-height:0.26in;"><div style="position:relative; left:0.40in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">of </span></SPAN></div><br/></div>
<div style="position:absolute;top:3.64in;left:0.47in;width:0.99in;line-height:0.26in;"><div style="position:relative; left:0.58in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Birth</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:3.85in;left:0.47in;width:1.42in;line-height:0.23in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">January </span></SPAN><br/></div>
<div style="position:absolute;top:3.85in;left:0.47in;width:1.42in;line-height:0.23in;"><div style="position:relative; left:0.66in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">20th </span></SPAN></div><br/></div>
<div style="position:absolute;top:3.85in;left:0.47in;width:1.42in;line-height:0.23in;"><div style="position:relative; left:1.04in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">1992</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:4.27in;left:0.47in;width:0.90in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Nationality</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:0.47in;width:1.60in;line-height:0.23in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">American </span></SPAN><br/></div>
<div style="position:absolute;top:4.49in;left:0.47in;width:1.60in;line-height:0.23in;"><div style="position:relative; left:0.78in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">– </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.49in;left:0.47in;width:1.60in;line-height:0.23in;"><div style="position:relative; left:0.93in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff">Nigerian</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:5.80in;left:0.47in;width:1.93in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Email</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.42in;left:0.47in;width:0.52in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Phone</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.03in;left:0.47in;width:1.81in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff">Address</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.01in;left:0.47in;width:1.93in;line-height:0.25in;"><a href="mailto:mylessigwe@gmail.com"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">mylessigwe@gmail.com</span></a>
<span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.61in;left:0.47in;width:1.38in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">+234 </span></SPAN><br/></div>
<div style="position:absolute;top:6.61in;left:0.47in;width:1.38in;line-height:0.25in;"><div style="position:relative; left:0.39in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">809 </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.61in;left:0.47in;width:1.38in;line-height:0.25in;"><div style="position:relative; left:0.71in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">2354 </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.61in;left:0.47in;width:1.38in;line-height:0.25in;"><div style="position:relative; left:1.11in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">153</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.25in;left:0.47in;width:1.81in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">No </span></SPAN><br/></div>
<div style="position:absolute;top:7.25in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">78, </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.25in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.48in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Norman </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.25in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:1.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Williams</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.46in;left:0.47in;width:1.81in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Ikoyi, </span></SPAN><br/></div>
<div style="position:absolute;top:7.46in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.41in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Lagos, </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.46in;left:0.47in;width:1.81in;line-height:0.25in;"><div style="position:relative; left:0.92in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff">Nigeria.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:8.93in;left:0.47in;width:1.65in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">Caritas </span></SPAN><br/></div>
<div style="position:absolute;top:8.93in;left:0.47in;width:1.65in;line-height:0.30in;"><div style="position:relative; left:0.71in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">University</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.14in;left:0.47in;width:1.41in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">Bsc </span></SPAN><br/></div>
<div style="position:absolute;top:9.14in;left:0.47in;width:1.41in;line-height:0.30in;"><div style="position:relative; left:0.36in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">Economics</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.35in;left:0.47in;width:1.07in;line-height:0.31in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff">2009 </span></SPAN><br/></div>
<div style="position:absolute;top:9.35in;left:0.47in;width:1.07in;line-height:0.31in;"><div style="position:relative; left:0.48in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff">– </span></SPAN></div><br/></div>
<div style="position:absolute;top:9.35in;left:0.47in;width:1.07in;line-height:0.31in;"><div style="position:relative; left:0.64in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff">2013</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.99in;left:0.47in;width:1.63in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">Metropolitan </span></SPAN><br/></div>
<div style="position:absolute;top:9.99in;left:0.47in;width:1.63in;line-height:0.30in;"><div style="position:relative; left:1.22in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">Film</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:10.20in;left:0.47in;width:0.66in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff">School</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.41in;left:0.47in;width:0.94in;line-height:0.31in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff">2013-2014</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Poppins;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.25in;left:4.21in;width:1.65in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063">WORK </span></SPAN><br/></div>
<div style="position:absolute;top:3.25in;left:4.21in;width:1.65in;line-height:0.30in;"><div style="position:relative; left:0.59in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063">EXPERIENCE</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:5.98in;left:4.21in;width:1.76in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063">PERSONAL </span></SPAN><br/></div>
<div style="position:absolute;top:5.98in;left:4.21in;width:1.76in;line-height:0.30in;"><div style="position:relative; left:0.93in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063">PROJECT</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.83in;left:4.21in;width:1.00in;line-height:0.30in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063">LANGUAGE</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Poppins Medium;color:#375063"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.68in;left:4.21in;width:3.79in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">Eclipse </span></SPAN><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:0.51in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ipsum </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.02in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolor </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sit </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.67in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">amet, </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:2.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">consectetuer </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">adipiscing </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.24in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:4.03in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">elit,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sed </span></SPAN><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">diam </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:0.75in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nonummy </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.58in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nibh </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.95in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">euismod </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:2.65in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">tincidunt </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.37in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ut </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.48in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.57in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">laoreet</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolore </span></SPAN><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:0.53in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">magna </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.12in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">aliquam </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.80in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">erat </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:2.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">volutpat. </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:2.86in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">Ut </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.05in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">wisi </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.37in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">enim </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.71in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:3.79in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ad</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:4.94in;left:4.21in;width:4.32in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">minim </span></SPAN><br/></div>
<div style="position:absolute;top:4.94in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:0.52in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">veniam, </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.94in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">quis </span></SPAN></div><br/></div>
<div style="position:absolute;top:4.94in;left:4.21in;width:4.32in;line-height:0.25in;"><div style="position:relative; left:1.52in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nostrud.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:6.46in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">Lorem </span></SPAN><br/></div>
<div style="position:absolute;top:6.46in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.51in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ipsum </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.46in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.02in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolor </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.46in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sit </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.46in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.67in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">amet,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:6.69in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">consectetuer </span></SPAN><br/></div>
<div style="position:absolute;top:6.69in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.06in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">adipiscing </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.69in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.89in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">elit,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:6.92in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sed </span></SPAN><br/></div>
<div style="position:absolute;top:6.92in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">diam </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.92in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.75in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nonummy </span></SPAN></div><br/></div>
<div style="position:absolute;top:6.92in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.58in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nibh</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.16in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">euismod </span></SPAN><br/></div>
<div style="position:absolute;top:7.16in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.70in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">tincidunt </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.16in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.42in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ut </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.16in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.61in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">laoreet</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.39in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolore </span></SPAN><br/></div>
<div style="position:absolute;top:7.39in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.53in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">magna </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.39in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.12in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">aliquam </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.39in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.80in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">erat</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">volutpat. </span></SPAN><br/></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.71in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">Ut </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.90in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">wisi </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.22in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">enim </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.65in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ad </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.62in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.89in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">minim</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:7.85in;left:5.73in;width:2.41in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">veniam, </span></SPAN><br/></div>
<div style="position:absolute;top:7.85in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:0.64in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">quis </span></SPAN></div><br/></div>
<div style="position:absolute;top:7.85in;left:5.73in;width:2.41in;line-height:0.25in;"><div style="position:relative; left:1.00in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nostrud.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:10.26in;left:4.21in;width:0.60in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">Yoruba</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.26in;left:6.63in;width:0.59in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">English</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.63in;left:4.21in;width:0.53in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">Hausa</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.63in;left:6.63in;width:0.57in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">French</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.00in;left:4.21in;width:0.38in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">Igbo</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.00in;left:6.63in;width:0.52in;line-height:0.26in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b">Pidgin</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Poppins;color:#3c3c3b"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.34in;left:5.73in;width:2.19in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">Lorem </span></SPAN><br/></div>
<div style="position:absolute;top:8.34in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:0.51in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ipsum </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.34in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.02in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolor </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.34in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sit </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.34in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.67in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">amet,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:8.58in;left:5.73in;width:2.19in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">consectetuer </span></SPAN><br/></div>
<div style="position:absolute;top:8.58in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.06in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">adipiscing </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.58in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.89in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">elit,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:8.81in;left:5.73in;width:2.19in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">sed </span></SPAN><br/></div>
<div style="position:absolute;top:8.81in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">diam </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.81in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:0.75in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nonummy </span></SPAN></div><br/></div>
<div style="position:absolute;top:8.81in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.58in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">nibh</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.04in;left:5.73in;width:2.19in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">euismod </span></SPAN><br/></div>
<div style="position:absolute;top:9.04in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:0.70in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">tincidunt </span></SPAN></div><br/></div>
<div style="position:absolute;top:9.04in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.42in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">ut </span></SPAN></div><br/></div>
<div style="position:absolute;top:9.04in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.61in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">laoreet</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<div style="position:absolute;top:9.27in;left:5.73in;width:2.19in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">dolore </span></SPAN><br/></div>
<div style="position:absolute;top:9.27in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:0.53in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">magna </span></SPAN></div><br/></div>
<div style="position:absolute;top:9.27in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.12in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">aliquam </span></SPAN></div><br/></div>
<div style="position:absolute;top:9.27in;left:5.73in;width:2.19in;line-height:0.25in;"><div style="position:relative; left:1.80in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041">erat</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Poppins Medium;color:#404041"> </span><br/></SPAN></div></div>
<img style="position:absolute;top:11.87in;left:7.42in;width:1.16in;height:0.52in" src="{{$records->rootFolder}}/ci_5.png" />
<img style="position:absolute;top:10.34in;left:4.91in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_6.png" />
<img style="position:absolute;top:10.34in;left:4.91in;width:0.60in;height:0.09in" src="{{$records->rootFolder}}/ci_7.png" />
<img style="position:absolute;top:10.34in;left:7.32in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_8.png" />
<img style="position:absolute;top:10.34in;left:7.32in;width:0.76in;height:0.09in" src="{{$records->rootFolder}}/ci_9.png" />
<img style="position:absolute;top:10.71in;left:4.91in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_10.png" />
<img style="position:absolute;top:10.71in;left:4.91in;width:0.12in;height:0.09in" src="{{$records->rootFolder}}/ci_11.png" />
<img style="position:absolute;top:10.71in;left:7.32in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_12.png" />
<img style="position:absolute;top:11.09in;left:4.91in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_13.png" />
<img style="position:absolute;top:11.09in;left:4.91in;width:0.60in;height:0.09in" src="{{$records->rootFolder}}/ci_14.png" />
<img style="position:absolute;top:11.09in;left:7.32in;width:0.80in;height:0.09in" src="{{$records->rootFolder}}/ci_15.png" />
<img style="position:absolute;top:11.09in;left:7.32in;width:0.43in;height:0.09in" src="{{$records->rootFolder}}/ci_16.png" />
<img style="position:absolute;top:0.75in;left:0.00in;width:3.70in;height:2.79in;clip-path:circle();" src="{{asset($records->user->display_photo)}}" />

</body>
</html>
